apiVersion: v2
appVersion: v1.5.13
description: A Helm chart for rook ceph cluster CRD
name: rook-ceph-cluster
version: 1.5.1
icon: https://rook.io/images/rook-logo.svg
sources:
- https://github.com/rook/rook
maintainers:
- name: mkhpalm
  email: mkhpalm@gmail.com
keywords:
- rook
- ceph
